### ISSUE TITLE
Standalone not working

### ISSUE THREAD

**Issue by Travincebarker** [albertomr86/python-logging-rabbitmq#12]
Hello everybody, 

I'm trying to implement your lib in my python app. We're not using Django and we have this error raised : 

`Traceback (most recent call last):
  File "/home/vgaugry/darwin/sms_v2_tools/sms_v2_tools/custom_logger/test.py", line 1, in <module>
    import DarwinLogger
  File "/home/vgaugry/darwin/sms_v2_tools/sms_v2_tools/custom_logger/DarwinLogger.py", line 4, in <module>
    from python_logging_rabbitmq import RabbitMQHandlerOneWay
  File "/home/vgaugry/.virtualenvs/sms-v2_env/local/lib/python2.7/site-packages/python_logging_rabbitmq/__init__.py", line 2, in <module>
    from .formatters import JSONFormatter  # noqa: F401
  File "/home/vgaugry/.virtualenvs/sms-v2_env/local/lib/python2.7/site-packages/python_logging_rabbitmq/formatters.py", line 5, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
ImportError: No module named django.core.serializers.json`

I simply followed the "standalone" part of the readme.
Is this normal ? Or Am I doing something wrong ? 

Thx !

**Comment by albertomr86** [comment]
Thanks for reporting this.

I need to separate that dependency in order to be able to use it without Django (at least without having to install Django).

I'll fix over the weekend.

**Comment by albertomr86** [comment]
A new version has been released that fixes this issue.

Please install version 1.1.1

```sh
pip install python-logging-rabbitmq==1.1.1
```
