### ISSUE TITLE
[django] AttributeError: 'socket' object has no attribute 'POST'

### ISSUE THREAD

**Issue by cumulus13** [albertomr86/python-logging-rabbitmq#34]
i got this error:

```bash
--- Logging error ---
Traceback (most recent call last):
NoneNone  File "D:\projects\dtp\env\lib\site-packages\python_logging_rabbitmq\handlers.py", line 159, in emit
    no_exc_record.traceback = reporter.get_traceback_text()
  File "D:\projects\dtp\env\lib\site-packages\django\views\debug.py", line 403, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "D:\projects\dtp\env\lib\site-packages\django\views\debug.py", line 364, in get_traceback_data
    self.filter.get_post_parameters(self.request).items()
  File "D:\projects\dtp\env\lib\site-packages\django\views\debug.py", line 209, in get_post_parameters
    return request.POST
AttributeError: 'socket' object has no attribute 'POST'
Call stack:
  File "c:\sdk\Anaconda3\lib\threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "c:\sdk\Anaconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "c:\sdk\Anaconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\sdk\Anaconda3\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\sdk\Anaconda3\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\sdk\Anaconda3\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "D:\projects\dtp\env\lib\site-packages\django\core\servers\basehttp.py", line 204, in handle
    self.handle_one_request()
  File "D:\projects\dtp\env\lib\site-packages\django\core\servers\basehttp.py", line 227, in handle_one_request
    handler.run(self.server.get_app())
  File "c:\sdk\Anaconda3\lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "c:\sdk\Anaconda3\lib\wsgiref\handlers.py", line 196, in finish_response
    self.close()
  File "D:\projects\dtp\env\lib\site-packages\django\core\servers\basehttp.py", line 148, in close
    super().close()
  File "c:\sdk\Anaconda3\lib\wsgiref\simple_server.py", line 34, in close
    self.request_handler.log_request(
  File "c:\sdk\Anaconda3\lib\http\server.py", line 542, in log_request
    self.log_message('"%s" %s %s',
  File "D:\projects\dtp\env\lib\site-packages\django\core\servers\basehttp.py", line 187, in log_message
    level(format, *args, extra=extra)
  File "c:\sdk\Anaconda3\lib\logging\__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "c:\sdk\Anaconda3\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "c:\sdk\Anaconda3\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "c:\sdk\Anaconda3\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "c:\sdk\Anaconda3\lib\logging\__init__.py", line 952, in handle
    self.emit(record)
  File "D:\projects\dtp\env\lib\site-packages\python_logging_rabbitmq\handlers.py", line 178, in emit
    self.handleError(record)
Message: '"%s" %s %s'
Arguments: ('GET /favicon.ico HTTP/1.1', '404', '3919')
```

**Comment by albertomr86** [comment]
@cumulus13, which is the Python version? Could you share the steps to reproduce the error?
